---

- name: Ensure openvpn key dir has the right permission
  file:
    path: "{{ openvpn_keydir }}"
    state: directory
    mode: 0o700
    owner: "{{ openvpn_user }}"

- name: Check if crl.pem exists
  stat:
    path: "{{ openvpn_crl_pem_file }}"
  register: crl_pem_file

- name: Configure server
  template:
    src: server.conf.j2
    dest: "{{ openvpn_etcdir }}/server.conf"
    mode: 0o644
  notify: openvpn restart

# Needed by both tls-authentication tasks and client-configuration tasks. Placed
# here to avoid repeating it twice in both places where the tls and
# client-config tasks are located.
- name: Create client configuration directory
  file:
    path: "{{ openvpn_etcdir }}/ovpns"
    state: directory
    mode: 0o755
